services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_HOST_NAME: localhost:8080
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - config:/app/config
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: shifratordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  config: